language: python
cache: pip

python:
- 2.7
- 3.4
- 3.5
- 3.6

addons:
  mariadb: '10.1'
  postgres: '9.6'

env:
- DB=mysql
#- DB=postgres

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libmariadbd-dev libmariadbclient-dev

install:
- pip install -e .
- pip install mysqlclient psycopg2-binary coveralls

before_script:
- sh -c "cp testing/config/settings/travis.$DB.local.py testing/config/settings/local.py; fi"
- mkdir testing/log testing/download
- mysql < testing/sql/mysql.sql
#- psql < testing/sql/postgres.sql

script:
- coverage run testing/runtests.py

after_success:
- coveralls
