language: python
cache: pip

python:
- 2.7
- 3.4
- 3.5
- 3.6

addons:
  mariadb: '10.1'
  postgresql: '9.6'

env:
- DB=mysql
- DB=postgres

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libmariadbd-dev libmariadbclient-dev

install:
- pip install -e .
- pip install mysqlclient psycopg2-binary coveralls

before_script:
- sh -c "cp testing/config/settings/$DB.local.py testing/config/settings/local.py; fi"
- mkdir testing/log testing/download
- mysql < testing/sql/mysql.sql
- psql -U postgres -c 'CREATE DATABASE test_daiquiri_data;'
- psql -U postgres -f testing/sql/postgres.sql test_daiquiri_data

script:
- coverage run testing/runtests.py -k

after_success:
- coveralls
