language: python
cache:
  directories:
  - $HOME/virtualenv
service:
  - mysql
python:
- 2.7
- 3.4
install:
- pip install -r testing/requirements.txt
- pip install coveralls
before_script:
- cp testing/config/settings/travis.local.py testing/config/settings/local.py
script:
- coverage run runtests.py
after_success:
- coveralls
