language: python
cache:
  directories:
  - $HOME/virtualenv
addons:
  mariadb: '10.1'
python:
- 2.7
- 3.4
install:
- pip install -r testing/requirements.txt
- pip install coveralls
before_script:
- cp testing/config/travis.local.py testing/config/local.py
script:
- coverage run runtests.py
after_success:
- coveralls
