language: python
cache: pip

service:
  - mysql

python:
- 2.7
- 3.4
- 3.5
- 3.6

install:
- mkdir testing/log
- pip install -e .
- pip install mysqlclient
- pip install coveralls

before_script:
- cp testing/config/settings/travis.local.py testing/config/settings/local.py
- mysql -e 'CREATE DATABASE daiquiri_data_obs'
- mysql -e 'CREATE DATABASE daiquiri_data_sim'
- mysql daiquiri_data_obs < testing/sql/daiquiri_data_obs.sql
- mysql daiquiri_data_sim < testing/sql/daiquiri_data_sim.sql

script:
- coverage run testing/runtests.py

after_success:
- coveralls
