language: python
cache: pip

service:
  - mysql

python:
- 2.7
- 3.4
- 3.5
- 3.6

install:
- mkdir testing/log
- pip install -e .
- pip install mysqlclient
- pip install coveralls

before_script:
- cp testing/config/settings/travis.local.py testing/config/settings/local.py

script:
- coverage run testing/runtests.py

after_success:
- coveralls
